name: Terraform Module Releaser
on:
  pull_request:
    types: [opened, reopened, synchronize, closed] # Closed required
    branches:
      - main

permissions:
  contents: write # Required for to push tags, create release, and push changes to the wiki
  pull-requests: write # Required to comment on pull request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Terraform Module Releaser
        uses: techpivot/terraform-module-releaser@v1
        with:
          major-keywords: major update,breaking change
          minor-keywords: feat,feature
          patch-keywords: fix,chore
          default-first-tag: v1.0.0
          terraform-docs-version: v0.20.0
          delete-legacy-tags: true
          wiki-sidebar-changelog-max: 5
          module-change-exclude-patterns:  ".gitignore,*.md,*.tftest.hcl,tests/**,examples/**"
          module-asset-exclude-patterns:  ".gitignore,*.md,*.tftest.hcl,tests/**,examples/**"
          module-path-ignore: "**/examples,**/examples/**,**/tests,**/tests/**,**/docs/**,**/docs"